### ISSUE TITLE
How can I use EZCode-Adal-Angular5 to authenticate a user based on the tenant selection

### ISSUE THREAD

**Issue by teachall2026** [frankchen76/EZCode-Adal-Angular5#1]
Hi Frankchen76, 

Thanks for this library and really appreciate the work!

Please note this is not an issue but request for details on implementation.

I have the following requirements to authenticate a user:
1. Say I have two tenants - Tenant A and Tenant B, how can I utilize this library to dynamically authenticate the user against a tenant depending upon user's selection of a tenant. 
2. How can I extend this library to dynamically authenticate against Graph API based on his earlier selection?

Can you please let me know if it is feasible to authenticate based on above requirements and if yes, can you provide some high level implementation details?

Thanks.

**Comment by frankchen76** [comment]
@mvpkreddy , thanks for your using my library. Currently, since the EZCodeAdalModule is using forRoot to initialize the internal adal AuthenticationContext. it doesn't support passing config from actual caller programmatically. I'll add this request as a enhancement and let you know once it's implemented. 
Basically, when you look at the source code of EZCodeAdalService, you'll see the context is internal variable. what I am going to do is to create a public method in EZCodeAdalService like the following: 
`    public set Config(config: EZCodeAdalConfig){
        this.context.config=config;
    }
`
you can rely on Angular to inject EZCodeAdalService to your service call and set the config before you actually call the REST API. I am assuming once user selects a tenant, your application is probably going to use that tenant for the rest of application based on the requirement you mentioned above.

**Comment by teachall2026** [comment]
Thanks frankchen76 for your response. Can you please let me if there is any update on this request?

Yes, once the tenant is selected the user will continue the same for the rest of the application.

**Comment by frankchen76** [comment]
@mvpkreddy sorry to get back to you late. I updated my code to include a Config property in EZCodeAdalService so that you can change your adal configuration at run time. Please check the latest one from [ezcode-adal-angular5(1.0.9)@npm](https://www.npmjs.com/package/ezcode-adal-angular5) and [EZCode-Adal-Angular5 Github](https://github.com/frankchen76/EZCode-Adal-Angular5). Post your questions if you have. Thanks again for using this library.

**Comment by teachall2026** [comment]
@frankchen76 Thanks for looking into the issue but the solution provided isn't working as it is taking the default config passed to the module on callback (it is calling the constructor of adal service and taking the default config) and ignoring the one specified during runtime.

**Comment by frankchen76** [comment]
@mvpkreddy I had a little bit deep analysis for dynamically configuring adal settings and found out it might need more effort than what I thought. The reason for that is for a SPA, we can configure the adal library to dynamically use different configs at run time. However when Azure redirect back to our page and the page refresh happens (all things are reset), The adal needs to initialize the ADAL Context to be able to process the id-token. Without reading that config from a variable, the adal lib doesn't understand how to initialize. For this case, we probably have to rely on localStorage to store that config so that my code understands how to initialize the adal. 
another thing you might try is to check msal.js built on Azure AD v2.0 [Call the Microsoft Graph API from a JavaScript Single Page Application (SPA)](https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa).
